set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/pdk/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/pdk/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper"
set ::env(DESIGN_NAME) "user_project_wrapper"
set ::env(VERILOG_FILES) "/home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/../../verilog/rtl/defines.v /home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/../../verilog/rtl/user_project_wrapper.v"
set ::env(RUN_VERILATOR) "0"
set ::env(QUIT_ON_SYNTH_CHECKS) "0"
set ::env(ROUTING_CORES) "1"
set ::env(CLOCK_PERIOD) "25"
set ::env(CLOCK_PORT) "wb_clk_i"
set ::env(FP_PDN_MACRO_HOOKS) "mprj vccd2 vssd2 vccd2 vssd2"
set ::env(MACRO_PLACEMENT_CFG) "/home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/macro.cfg"
set ::env(VERILOG_FILES_BLACKBOX) "/home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/../../verilog/gl/aes_example.v"
set ::env(EXTRA_LEFS) "/home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/../../lef/aes_example.lef"
set ::env(EXTRA_GDS_FILES) "/home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/../../gds/aes_example.gds"
set ::env(EXTRA_SPEFS) "aes_example /home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/../../spef/multicorner/aes_example.min.spef /home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/../../spef/multicorner/aes_example.nom.spef /home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/../../spef/multicorner/aes_example.max.spef"
set ::env(BASE_SDC_FILE) "/home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/base_user_project_wrapper.sdc"
set ::env(IO_SYNC) "0"
set ::env(FP_PDN_CHECK_NODES) "0"
set ::env(SYNTH_ELABORATE_ONLY) "1"
set ::env(PL_RANDOM_GLB_PLACEMENT) "1"
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) "0"
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) "0"
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) "0"
set ::env(FP_PDN_ENABLE_RAILS) "0"
set ::env(GRT_REPAIR_ANTENNAS) "0"
set ::env(RUN_FILL_INSERTION) "0"
set ::env(RUN_TAP_DECAP_INSERTION) "0"
set ::env(FP_PDN_VPITCH) "81.6"
set ::env(FP_PDN_HPITCH) "81.6"
set ::env(RUN_CTS) "0"
set ::env(FP_PDN_VOFFSET) "5"
set ::env(FP_PDN_HOFFSET) "5"
set ::env(MAGIC_ZEROIZE_ORIGIN) "0"
set ::env(FP_SIZING) "absolute"
set ::env(RUN_CVC) "0"
set ::env(UNIT) "2.4"
set ::env(FP_IO_VEXTEND) "4.8"
set ::env(FP_IO_HEXTEND) "4.8"
set ::env(FP_IO_VLENGTH) "2.4"
set ::env(FP_IO_HLENGTH) "2.4"
set ::env(FP_IO_VTHICKNESS_MULT) "4"
set ::env(FP_IO_HTHICKNESS_MULT) "4"
set ::env(FP_PDN_CORE_RING) "1"
set ::env(FP_PDN_CORE_RING_VWIDTH) "3.1"
set ::env(FP_PDN_CORE_RING_HWIDTH) "3.1"
set ::env(FP_PDN_CORE_RING_VOFFSET) "12.45"
set ::env(FP_PDN_CORE_RING_HOFFSET) "12.45"
set ::env(FP_PDN_CORE_RING_VSPACING) "1.7"
set ::env(FP_PDN_CORE_RING_HSPACING) "1.7"
set ::env(FP_PDN_VWIDTH) "3.2"
set ::env(FP_PDN_HWIDTH) "3.2"
set ::env(FP_PDN_VSPACING) "3.2"
set ::env(FP_PDN_HSPACING) "3.2"
set ::env(VDD_NETS) "vccd1 vccd2 vdda1 vdda2"
set ::env(GND_NETS) "vssd1 vssd2 vssa1 vssa2"
set ::env(SYNTH_USE_PG_PINS_DEFINES) "USE_POWER_PINS"
set ::env(MAGIC_DEF_LABELS) "0"
set ::env(RT_MAX_LAYER) "met4"
set ::env(DIE_AREA) "0 0 2920 3520"
set ::env(FP_DEF_TEMPLATE) "/home/hosni/AES/caravel_aes_example/openlane/user_project_wrapper/fixed_dont_change/user_project_wrapper.def"
